on: 
  push:
    branches:
      - master
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.ftp_host }}
        username: ${{ secrets.ftp_user }}
        password: ${{ secrets.ftp_password }}
        server-dir: public_html/SystemFinance
        exclude: 
        - .env
        - /vendor/
        - /.idea
        - /.vscode
        - /.vagrant
        - Homestead.json
        - Homestead.yaml
        - npm-debug.log
        - package-lock.json
        - yarn-error.log
        - .phpunit.result.cache
        - /node_modules
        - /public/hot
        - /public/storage
        - /storage/*.key